package com.bruno.bootcampheroes.documents;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import static com.bruno.bootcampheroes.constants.HeroConstant.HERO_TABLE_NAME;

@DynamoDBDocument
@DynamoDBTable(tableName = HERO_TABLE_NAME)
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class HeroDocument {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "role")
    private String role;

    @DynamoDBAttribute(attributeName = "media")
    private String media;
}
